baseURL = "https://xushun1221.github.io"
# website language
languageCode = "en"
# [en, zh, ...] determines which i18n file to use
defaultContentLanguage = "en"
# website title
title = "XuShun's Blog"
# theme
theme = "LoveIt"
# whether to use git commit log to generate lastmod record
enableGitInfo = false
# whether to include chinese/japanese/korean
hasCJKLanguage = true
# default amount of posts in each pages
paginate = 10
# whether to use emoji code
enableEmoji = true
# whether to use robots.txt
enableRobotsTXT = true
# [UA-XXXXXXXX-X] google analytics code
googleAnalytics = "UA-209130979-1"
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# date format
dateFormatToUse = "2006-01-02"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "shuzang"
  link = "https://shuzang.github.io/about/"

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:slug"

# Menu Info
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 4

  # [[menu.main]]
  #   identifier = "zh"
  #   pre = '<i class="fas fa-language fa-fw"></i>'
  #   name = ""
  #   title = "简体中文"
  #   url = "https://hugo-loveit-zh.netlify.com"
  #   weight = 5

[params]
  # LoveIt theme version
  version = "0.1.X"

